font_family CaskaydiaCove Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
enable_audio_bell no
font_size 9.0
window_padding_width 25
cursor_trail 1

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Background Opacity
background_opacity 0.5
dynamic_background_opacity yes   

# Color Theme
color0 #333366
color1 #6666cc
color2 #0099cc
color3 #3366cc
color4 #006699
color5 #0066ff
color6 #669999
color7 #99cccc
color8 #333399
color9 #9999ff
color10 #00ccff
color11 #6699ff
color12 #0099cc
color13 #0099ff
color14 #66cccc
color15 #ccffff
foreground #666699
background #000000

# remap to open new kitty tab in the same directory (default is home dir)
# map ctrl+shift+t            new_tab_with_cwd

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
# sync_to_monitor no
# wayland_enable_ime no
