wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpaper/Desktop/wallhaven-mlzzx8.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpaper/Mobile/wallhaven-728vje.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-3
    path = ~/Pictures/Wallpaper/Mobile/wallhaven-xe8pwd.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpaper/Desktop/wallhaven-l38kvy.png
    fit_mode = cover
}
