-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    wallpaper = {
        path = "~/Pictures/Wallpaper/Desktop/wallhaven-mlzzx8.png",
        fit_mode = "cover",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output

hl.config({
    wallpaper = {
        path = "~/Pictures/Wallpaper/Mobile/wallhaven-728vje.jpg",
        fit_mode = "cover",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output

hl.config({
    wallpaper = {
        path = "~/Pictures/Wallpaper/Mobile/wallhaven-xe8pwd.png",
        fit_mode = "cover",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output

hl.config({
    wallpaper = {
        path = "~/Pictures/Wallpaper/Desktop/wallhaven-l38kvy.png",
        fit_mode = "cover",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output
