-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMonitor = "DP-5"

local topMonitor = "HDMI-A-3"

local verticalMonitor = "DP-4"

hl.monitor({
    output   = "$mainMonitor",
    mode     = "2560x1440@144",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "$topMonitor",
    mode     = "1920x1080",
    position = "300x-1080",
    scale    = 1,
})

hl.monitor({
    output   = "$verticalMonitor",
    mode     = "2560x1440@75",
    position = "-1440x-500",
    scale    = 1,
    transform = 1,
})

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "1920x515",
    position = "10000x0",
    scale    = 1,
    transform = 1,
})
