-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
-- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

-- See https://wiki.hyprland.org/Configuring/Window-Rules/

--? ------- WINDOWRULES_HYPRLAND_V_0_53 COMPATIBLE ----------------

--   This Config is compatible with windowrules changes in Hyprland v0.53+

--   Any future breaking changes disables this block and notifies the user to update.

--   User template files will be provided in $XDG_DATA_HOME/hyde/templates/hypr/windowrules.conf for manual update.

-- hyprlang if WINDOWRULES_HYPRLAND_V_0_53

-- idle_inhibit rules

hl.window_rule({
    name  = "idle_inhibit_fullscr",
    match = {
        class = "^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$",
    },
    idle_inhibit = "fullscreen"
})

hl.window_rule({
    name  = "idle_inhibit_fullscr",
    match = {
        class = "^(.*[Ss]potify.*)$",
    },
    idle_inhibit = "fullscreen"
})

hl.window_rule({
    name  = "idle_inhibit_fullscr",
    match = {
        class = "^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$",
    },
    idle_inhibit = "fullscreen"
})

-- Picture-in-Picture

hl.window_rule({
    name  = "hyde_picture_in_picture",
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
    },
    tag = "+hyde_picture_in_picture",
    float = true,
    keep_aspect_ratio = true,
    move = { "(monitor_w*0.73)", "(monitor_h*0.72)" },
    size = { "(monitor_w*0.25)", "(monitor_h*0.25)" },
    pin = true,
})

hl.window_rule({
    name  = "opacity_0_90____0_90",
    match = {
        class = "^(firefox)$",
    },
    opacity = "0.90 0.90 1",
})

hl.window_rule({
    name  = "opacity_0_90____0_90",
    match = {
        class = "^(brave-browser)$",
    },
    opacity = "1 0.90 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(code-oss)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^([Cc]ode)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(code-url-handler)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(code-insiders-url-handler)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name    = "opacity_0_80____0_80",
    float = true,
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(org.kde.dolphin)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(org.kde.ark)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(nwg-look)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(qt5ct)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(qt6ct)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_80",
    match = {
        class = "^(kvantummanager)$",
    },
    opacity = "0.80 0.80 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(org.pulseaudio.pavucontrol)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(blueman-manager)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(nm-applet)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(nm-connection-editor)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(polkit-gnome-authentication-agent-1)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(org.freedesktop.impl.portal.desktop.gtk)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_80____0_70",
    match = {
        class = "^(org.freedesktop.impl.portal.desktop.hyprland)$",
    },
    opacity = "0.80 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_70____0_70",
    match = {
        class = "^([Ss]team)$",
    },
    opacity = "0.70 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_70____0_70",
    match = {
        class = "^(steamwebhelper)$",
    },
    opacity = "0.70 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_70____0_70",
    match = {
        class = "^([Ss]potify)$",
    },
    opacity = "0.70 0.70 1",
})

hl.window_rule({
    name  = "opacity_0_90_0_90",
    match = {
        class = "^(com.github.rafostar.Clapper)$",
    },
    opacity = "0.90 0.90",
})

-- Clapper-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(com.github.tchx84.Flatseal)$",
    },
    opacity = "0.80 0.80",
})

-- Flatseal-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(hu.kramo.Cartridges)$",
    },
    opacity = "0.80 0.80",
})

-- Cartridges-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(com.obsproject.Studio)$",
    },
    opacity = "0.80 0.80",
})

-- Obs-Qt

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(gnome-boxes)$",
    },
    opacity = "0.80 0.80",
})

-- Boxes-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(vesktop)$",
    },
    opacity = "0.80 0.80",
})

-- Vesktop

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(discord)$",
    },
    opacity = "0.80 0.80",
})

-- Discord-Electron

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(WebCord)$",
    },
    opacity = "0.80 0.80",
})

-- WebCord-Electron

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(ArmCord)$",
    },
    opacity = "0.80 0.80",
})

-- ArmCord-Electron

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(app.drey.Warp)$",
    },
    opacity = "0.80 0.80",
})

-- Warp-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(net.davidotek.pupgui2)$",
    },
    opacity = "0.80 0.80",
})

-- ProtonUp-Qt

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(yad)$",
    },
    opacity = "0.80 0.80",
})

-- Protontricks-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(Signal)$",
    },
    opacity = "0.80 0.80",
})

-- Signal-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(io.github.alainm23.planify)$",
    },
    opacity = "0.80 0.80",
})

-- planify-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(io.gitlab.theevilskeleton.Upscaler)$",
    },
    opacity = "0.80 0.80",
})

-- Upscaler-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(com.github.unrud.VideoDownloader)$",
    },
    opacity = "0.80 0.80",
})

-- VideoDownloader-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(io.gitlab.adhami3310.Impression)$",
    },
    opacity = "0.80 0.80",
})

-- Impression-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(io.missioncenter.MissionCenter)$",
    },
    opacity = "0.80 0.80",
})

-- MissionCenter-Gtk

hl.window_rule({
    name  = "opacity_0_80_0_80",
    match = {
        class = "^(io.github.flattool.Warehouse)$",
    },
    opacity = "0.80 0.80",
})

-- Warehouse-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(Signal)$",
    },
    float = true
})

-- Signal-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(com.github.rafostar.Clapper)$",
    },
    float = true
})

-- Clapper-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(app.drey.Warp)$",
    },
    float = true
})

-- Warp-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(net.davidotek.pupgui2)$",
    },
    float = true
})

-- ProtonUp-Qt

hl.window_rule({
    name = "float_true",
    match = {
        class = "^(yad)$",
    },
    float = true
})

-- Protontricks-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(eog)$",
    },
    float = true
})

-- Imageviewer-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(io.github.alainm23.planify)$",
    },
    float = true
})

-- planify-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(io.gitlab.theevilskeleton.Upscaler)$",
    },
    float = true
})

-- Upscaler-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(com.github.unrud.VideoDownloader)$",
    },
    float = true
})

-- VideoDownloader-Gkk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(io.gitlab.adhami3310.Impression)$",
    },
    float = true
})

-- Impression-Gtk

hl.window_rule({
    name  = "float_true",
    match = {
        class = "^(io.missioncenter.MissionCenter)$",
    },
    float = true
})

-- MissionCenter-Gtk

-- workaround for jetbrains IDEs dropdowns/popups cause flickering

hl.window_rule({
    name  = "no_initial_focus_tru",
    match = {
        title = "^(win[0-9]+)$",
    },
    no_initial_focus = true
})

hl.window_rule({
    name  = "float_true",
    match = {
        title = "^([Pp]icture.[Ii]n.[Pp]icture)",
    },
    float = true
})

-- █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀

-- █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "notifications",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "notifications",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "swaync-notification-window",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "swaync-notification-window",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "logout_dialog",
    },
    blur = true,
})

-- hyprlang endif
