-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local primary_paletteKeyColor = "28828e"

local secondary_paletteKeyColor = "5f7c81"

local tertiary_paletteKeyColor = "8a6aa3"

local neutral_paletteKeyColor = 747879

local neutral_variant_paletteKeyColor = "6e797b"

local background = 101415

local onBackground = "e0e3e4"

local surface = 101415

local surfaceDim = 101415

local surfaceBright = "363a3b"

local surfaceContainerLowest = "0b0f10"

local surfaceContainerLow = "181c1d"

local surfaceContainer = "1c2021"

local surfaceContainerHigh = "272b2b"

local surfaceContainerHighest = 313536

local onSurface = "e0e3e4"

local surfaceVariant = "3e494a"

local onSurfaceVariant = "bec8ca"

local inverseSurface = "e0e3e4"

local inverseOnSurface = "2d3132"

local outline = 889394

local outlineVariant = "3e494a"

local shadow = 000000

local scrim = 000000

local surfaceTint = "81d3e0"

local primary = "81d3e0"

local onPrimary = "00363d"

local primaryContainer = "28828e"

local onPrimaryContainer = 000608

local inversePrimary = 006874

local secondary = "adccd1"

local onSecondary = 173539

local secondaryContainer = "2f4b50"

local onSecondaryContainer = "9cbac0"

local tertiary = "ddb9f7"

local onTertiary = 402357

local tertiaryContainer = "a584bf"

local onTertiaryContainer = 000000

local error = "ffb4ab"

local onError = 690005

local errorContainer = "93000a"

local onErrorContainer = "ffdad6"

local primaryFixed = "9eeffd"

local primaryFixedDim = "81d3e0"

local onPrimaryFixed = "001f24"

local onPrimaryFixedVariant = "004f57"

local secondaryFixed = "c9e8ee"

local secondaryFixedDim = "adccd1"

local onSecondaryFixed = "001f24"

local onSecondaryFixedVariant = "2f4b50"

local tertiaryFixed = "f2daff"

local tertiaryFixedDim = "ddb9f7"

local onTertiaryFixed = "290c41"

local onTertiaryFixedVariant = "573a6f"

local term0 = 343434

local term1 = "8383ff"

local term2 = "44e1d5"

local term3 = "75fcdd"

local term4 = "76b4bd"

local term5 = "7aaee9"

local term6 = "80d8d8"

local term7 = "ccdcd6"

local term8 = "9aa59f"

local term9 = "a29eff"

local term10 = "13f7ea"

local term11 = "c9fff3"

local term12 = "a3c7ca"

local term13 = "a2c0f7"

local term14 = "87ecea"

local term15 = "ffffff"

local rosewater = "f1f3e5"

local flamingo = "dfe0f5"

local pink = "bae2ff"

local mauve = "6cccf4"

local red = "8ab5ff"

local maroon = "abbef0"

local peach = "a9daac"

local yellow = "d1faf1"

local green = "8af0f0"

local teal = "9fecf4"

local sky = "94e8f6"

local sapphire = "74d5e9"

local blue = "5fcae8"

local lavender = "8cd7f3"

local klink = "0094ac"

local klinkSelection = "0094ab"

local kvisited = "008bb6"

local kvisitedSelection = "008bb5"

local knegative = "607eff"

local knegativeSelection = "607eff"

local kneutral = "34c359"

local kneutralSelection = "34c359"

local kpositive = "00bcbf"

local kpositiveSelection = "00bcbd"

local text = "e0e3e4"

local subtext1 = "bec8ca"

local subtext0 = 889394

local overlay2 = 768081

local overlay1 = "646c6e"

local overlay0 = "535b5c"

local surface2 = "434a4b"

local surface1 = "33383a"

local surface0 = 212627

local base = 101415

local mantle = 101415

local crust = "0f1314"

local success = "B5CCBA"

local onSuccess = 213528

local successContainer = "374B3E"

local onSuccessContainer = "D1E9D6"
